# Generated by Django 4.2.18 on 2025-02-15 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
